apiVersion: v1
kind: Pod
metadata:
    name: formula-one
    namespace: dio
spec:
    containers:
        - name: formula-one
          image: formula-one:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3331