apiVersion: apps/v1
kind: Deployment

metadata:
  name: jenkins-node

spec:
  replicas: 1

  selector:
    matchLabels:
      app: jenkins-node

  template:
    metadata:
      labels:
        app: jenkins-node

    spec:
      containers:
      - name: jenkins-node
        image: jenkins-node:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 8081

        volumeMounts:
        - name: jenkins-storage
          mountPath: /var/jenkins_home
        - name: docker-sock
          mountPath: /var/run/docker.sock


      volumes:
      - name: jenkins-storage
        hostPath:
          path: /opt/jenkins
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock